### ISSUE TITLE
new maintainer

### ISSUE THREAD

**Issue by cody-greene** [cody-greene/scssify#10]
Looks like this project is in need of a new owner: I'm ready and willing, if only to get watchify support in.

**Comment by chrishoage** [comment]
Yes, I can transfer both this repo and the NPM package to you if you desire. What is your NPM username?

**Comment by cody-greene** [comment]
Awsome, let's do it! (npm: [cody-greene](https://www.npmjs.com/~/cody-greene))

**Comment by chrishoage** [comment]
It looks like you need to delete your fork if you want _this_ repo. I added you as a maintainer to the npm package.

**Comment by chrishoage** [comment]
Or rename your fork, it just won't let me transfer this repo because one of the same name exists on your account.

**Comment by cody-greene** [comment]
Alright I just removed my fork

**Comment by chrishoage** [comment]
Ah, thanks, you don't need to make me a Collaborator. I was actually going to remove myself as a contributor of the npm package. 

Thanks for taking this over!
