### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by rico345100** [cody-greene/scssify#24]
When I run gulp with scssify, it fails with

> Segmentation fault: 11

gulpfile.js:

```javascript
function buildJs() {
	let b = watchify(browserify({ ... }));
	.transform(babelify, { 
		presets: ["es2015", "react"],
		plugins: [
			"syntax-async-functions",
			"transform-regenerator"
		]
	})
	.transform(scssify, {
		autoInject: true
	});

	function bundle() {
		let stream = b.bundle()
		.on('error', swallowError)
		.pipe(source('index.js'))
		.pipe(buffer())
		.pipe(rename('bundle.js'));

		if(isProduction) {
			stream.pipe(uglify());
		}

		return stream.pipe(gulp.dest(`${DIST}/js`));
	}

	return bundle();
}
```

And this is component js file:

```javascript
import React, { Component } from 'react';
require('./style.css');

class Start extends Component {
	render() {
		return (
			<div id="view-start" className="component-view">
				<div>StartView</div>
			</div>
		);
	}
}

export default Start;
```

And style.css file in same directory with component js file:

```css
body {
	background-color: #ff0000;
}
```

I had reinstalled all node modules and even reinstall gulp globally, it didn't worked. When I removed those *require('./style.css')* from component js file, it worked(of course, no css/scss injected). Error only occurs when including scss/css file with import/require statement with scssify.

Using gulp v3.9.1, sass 3.4.18, scssify 2.2.0.

**Comment by cody-greene** [comment]
This is likely an issue with `node-sass` rather than `scssify`. Try running `node-sass` directly and see what you get:
```
$ node_modules/.bin/node-sass ./style.scss >out.css
```
Probably something to do with media-query nesting in your stylesheet ... `¯\_(ツ)_/¯`

**Comment by cody-greene** [comment]
Any progress with this?

**Comment by rico345100** [comment]
I tested with node-sass, no error out. Tested with node-sass v4.1.1, node v6.9.1.

**Comment by cody-greene** [comment]
Can you write a _complete_ minimal project that reproduces this? e.g. only add `gulp` or `babel` if it seems to be part of the problem. Include `package.json`, an entry script, a build script, and a stylesheet. 

```
// package.json
{
  "name": "foo",
  "private": true,
  "scripts": {
    "start": "browserify -t scssify app.js >bundle.js"
  },
  "dependencies": {
    ...
  }
}

// app.js
require('./styles.scss')
console.log('Hello, World!')

// styles.scss
...
```
