### ISSUE TITLE
postcss autoprefixer:  read browsers from .browserlistrc

### ISSUE THREAD

**Issue by mrcesc0** [cody-greene/scssify#33]
Hi all, i was wondering how to say to the autoprefixer to get the browserlist from .browserlistrc.
Here's my code:
`function getScssifyOptions() {
        return {
            autoInject: utils.isDevelopment() ? 'verbose' : true,
            sass: {
                sourceMapEmbed: utils.isDevelopment(),
                sourceMapContents: utils.isDevelopment(),
                outputStyle: utils.isProduction() ? 'compressed' : ''
            },
            postcss: {
                autoprefixer: {
                    browsers: ['last 2 versions']
                }
            }
        };
    }`
Thank you so much!

**Comment by cody-greene** [comment]
Take a look at https://github.com/postcss/autoprefixer
I don't maintain autoprefixer, and any properties in the `postcss` area pass straight through to your plugins.
