### ISSUE TITLE
Adding settings in package.json results in syntax error

### ISSUE THREAD

**Issue by DennisJohnsen** [cody-greene/scssify#34]
Hey.. 

I'm currently running this command to use scssify:
`"bundle": "watchify build/index.js -g ascjsify --s module -t scssify -o build/component.js",`

And it works perfectly. Problem is though, when i start adding settings in my `package.json`, like so:
```JSON
"browserify": {
        "transform": [
            [
                "scssify",
                {
                    "sass": {
                        "outputStyle": "compressed",
                        "includePaths": [
                            "node_modules"
                        ]
                    },
                    "postcss": {
                        "autoprefixer": {
                            "browsers": [
                                "> 1%",
                                "last 1 versions",
                                "safari >= 8",
                                "IE 11"
                            ]
                        }
                    }
                }
            ]
        ]
    }
```

and the syntax error is this:
```
SyntaxError: Error: Invalid CSS after "var css": expected selector, was '= "h2{font-size:200'
        on line 1 of scss/styles.scss
>> var css = "h2{font-size:200px}body{background-color:tomato}\n"
```

**Comment by cody-greene** [comment]
I suspect the scssify transform is running twice.

First time `var css = "..."` will be generated and cached, as expected.

Second time `var css = "..."` is returned from the ~browserify/watchify cache~ output of the first transform, passed along to node-sass, and fails.

This can happen if you configure the scssify transform in package.json as well as running `watchify ... -t scssify`. I suggest removing the redundant "-t scssify" parameter and simply run: 
```
watchify build/index.js -o build/component.js
```

Does this solve your problem?

**Comment by DennisJohnsen** [comment]
It did! Sorry for making an issue that just turned into me not understanding my own pipeline :P

Thank you so much Cody!
